let cachedVoice: SpeechSynthesisVoice | null = null;
let voicesReadyResolver: (() => void) | null = null;
const voicesReady: Promise<void> = new Promise((resolve) => {
  voicesReadyResolver = resolve;
});

function hasSpeech(): boolean {
  return typeof window !== 'undefined' && 'speechSynthesis' in window;
}

/**
 * Pick the best Korean voice available.
 * Priority order:
 *   1. ko-KR voice whose name contains both "Yuna" AND a premium marker
 *      ("premium" / "enhanced" / "neural") — e.g. "Yuna (Premium)"
 *   2. ko-KR voice whose name contains "Yuna" (standard Apple voice)
 *   3. ko-KR voice whose name contains "premium", "enhanced", or "neural"
 *   4. Any other ko-KR voice
 *   5. Any voice whose lang starts with "ko" (e.g. ko-KP)
 */
function selectVoice(): SpeechSynthesisVoice | null {
  if (cachedVoice) return cachedVoice;
  if (!hasSpeech()) return null;

  const voices = window.speechSynthesis.getVoices();
  if (voices.length === 0) return null;

  const koKr = voices.filter((v) => v.lang === 'ko-KR');
  const isYuna = (v: SpeechSynthesisVoice) => /yuna/i.test(v.name);
  const isPremium = (v: SpeechSynthesisVoice) => /premium|enhanced|neural/i.test(v.name);

  const yunaPremium = koKr.find((v) => isYuna(v) && isPremium(v));
  if (yunaPremium) return (cachedVoice = yunaPremium);

  const yuna = koKr.find(isYuna);
  if (yuna) return (cachedVoice = yuna);

  const premium = koKr.find(isPremium);
  if (premium) return (cachedVoice = premium);

  if (koKr.length > 0) return (cachedVoice = koKr[0]);

  const anyKo = voices.find((v) => v.lang.toLowerCase().startsWith('ko'));
  if (anyKo) return (cachedVoice = anyKo);

  return null;
}

function resolveReady() {
  if (voicesReadyResolver) {
    voicesReadyResolver();
    voicesReadyResolver = null;
  }
}

function tryLoadVoices() {
  if (!hasSpeech()) return;
  const voices = window.speechSynthesis.getVoices();
  if (voices.length > 0) {
    selectVoice();
    resolveReady();
  }
}

// Kick off voice loading. Some browsers (Chrome) populate asynchronously and
// only fire the voiceschanged event once they're ready; others (Safari) return
// voices synchronously on the first getVoices() call.
if (hasSpeech()) {
  tryLoadVoices();
  window.speechSynthesis.addEventListener('voiceschanged', () => {
    // Re-select: a better voice might have arrived in the async batch.
    cachedVoice = null;
    tryLoadVoices();
  });
  // Safety net: if voiceschanged never fires (rare, seen in older Edge/some
  // PWA contexts), stop waiting after 1.5s so speech still works.
  setTimeout(() => {
    tryLoadVoices();
    resolveReady();
  }, 1500);
}

function doSpeak(text: string) {
  try {
    window.speechSynthesis.cancel();
    const u = new SpeechSynthesisUtterance(text);
    u.lang = 'ko-KR';
    u.rate = 0.9; // slightly slower — clearer for learners
    u.pitch = 1.0;
    const v = selectVoice();
    if (v) u.voice = v;
    window.speechSynthesis.speak(u);
  } catch (e) {
    console.warn('speak failed', e);
  }
}

export function speak(text: string) {
  if (!hasSpeech()) return;

  // Fast path: voices are already loaded — speak immediately.
  if (cachedVoice || window.speechSynthesis.getVoices().length > 0) {
    doSpeak(text);
    return;
  }

  // Cold path: first call before voices loaded. Wait for them so we use the
  // best voice rather than whatever default the browser falls back to.
  voicesReady.then(() => doSpeak(text));
}

// ---------------------------------------------------------------------------
// Pre-recorded audio (characters + vocab words)
// ---------------------------------------------------------------------------

// Pre-baked m4a clips generated by scripts/generate-audio.sh (Hangul
// characters → /audio/hangul/) and scripts/generate-vocab-audio.sh (vocab
// words → /audio/vocab/), using macOS `say -v "Yuna (Premium)"`.
//
// Both share the same playback machinery below; cache and missing-set are
// keyed by URL so hangul and vocab keys can't collide.

const audioCache = new Map<string, HTMLAudioElement>();
const missingAudio = new Set<string>();
let currentAudio: HTMLAudioElement | null = null;

/**
 * Play a pre-recorded clip at `url`. If the file can't be loaded or played,
 * fall back to Web Speech via speak(text).
 *
 * Returns a promise that resolves when playback ends (or when the fallback
 * finishes dispatching). Never rejects — audio is a nice-to-have.
 */
function playPrerecordedAudio(text: string, url: string): Promise<void> {
  if (typeof window === 'undefined') return Promise.resolve();

  const fallback = () => {
    speak(text);
    return Promise.resolve();
  };

  if (missingAudio.has(url)) return fallback();

  let el = audioCache.get(url);
  if (!el) {
    el = new Audio(url);
    el.preload = 'auto';
    audioCache.set(url, el);
  }

  // Stop any currently-playing clip and any queued TTS so they don't overlap.
  if (currentAudio && currentAudio !== el) {
    currentAudio.pause();
    currentAudio.currentTime = 0;
  }
  if (hasSpeech()) {
    try { window.speechSynthesis.cancel(); } catch { /* noop */ }
  }

  currentAudio = el;
  el.currentTime = 0;

  return new Promise<void>((resolve) => {
    let settled = false;
    const done = () => {
      if (settled) return;
      settled = true;
      el!.removeEventListener('ended', done);
      el!.removeEventListener('error', onError);
      resolve();
    };
    const onError = () => {
      if (settled) return;
      settled = true;
      el!.removeEventListener('ended', done);
      el!.removeEventListener('error', onError);
      // Remember so we don't thrash retries — the file genuinely isn't there.
      missingAudio.add(url);
      audioCache.delete(url);
      fallback().then(resolve);
    };

    el!.addEventListener('ended', done);
    el!.addEventListener('error', onError);

    const p = el!.play();
    // In some browsers .play() returns a promise that rejects if autoplay is
    // blocked or the source failed to load. Handle both.
    if (p && typeof p.catch === 'function') {
      p.catch(onError);
    }
  });
}

export function playCharacterAudio(character: string): Promise<void> {
  return playPrerecordedAudio(
    character,
    `/audio/hangul/${encodeURIComponent(character)}.m4a`,
  );
}

export function playWordAudio(word: string): Promise<void> {
  return playPrerecordedAudio(
    word,
    `/audio/vocab/${encodeURIComponent(word)}.m4a`,
  );
}
